export const EMAIL_PHONE = "Phone number or email address";
export const ENTER_OTP = "Enter OTP";
export const NOTIFY_MESSAGE = "I want to recieve notification of WhatsApp";
export const USER_NAME = "Username";
export const PHONE_NUMBER = "Phone Number";
export const EMAIL_ID = "Email ID";
export const AGE = "Age";
export const GENDER = "Gender";
export const USER_EXIST = "Have an account ?";
export const EMAIL_ERROR1 = "Email can't be empty";
export const EMAIL_ERROR2 = "Email address is not valid";
export const HOME_COVER = "infinite possibilities";
export const WORSHOP1 = "Attend . Discover";
export const QUOTE1 = "to do what you love"
export const QUOTE2 = "to learn more and earn more"
export const workshopNum = "15+"
export const WorkShop = "Workshop"
export const GatedNumb = "10+"
export const GatedContent = "Gated Content"
export const MyGatedContent = "My Gated Content"
export const WorkShopSubHead = "Sometimes you need answers. Sometimes fresh ideas And sometimes just a spark  of  inspiration. Workshops are the safe space for it all. You can learn new thngs here or just  find answers to old questions."
export const RecWorkShop = "Upcoming Workshop"
export const ViewWorkShop = "VIEW ALL WORKSHOP"
export const HostWorshp = "You can attend or host workshops. These are paid and yet another way to help creators learn or earn money."
export const step1 = "Create a workshop on any subject of your choice and set a price"
export const HostWorkshops = "Host Workshop"
export const EarnMoney = "Earn Money"
export const CREATEWORKSHOPS = "CREATE WORKSHOP"
export const reviewContent = "It was my first workshop ever! Must admit, I was sceptical when DYT came to me with the idea of hosting a workshop, not any more though. It was surreal and it went well. Loved the audience's enthusiasm and participation. Host: Learn The Techniques of Law Of Attraction & Manifest Your Dreams"
export const gatedcontentreview = "Hosting a workshop was a move out of my comfort zone. Awkward at first, but then what a boost of confidence! I connected with my audience and loved the questions they had. To add to it, the team at DYT made the whole experience really smooth."
export const GatedSubHeading = "Gated content is exclusive, paid content that you can sell to your community. To unlock the content, a user has to purchase the content from you."
export const Gstep1 = "Exclusive content can be an image, a video, or anything else"
export const Gstep2 = "Set a price to it and an expiry date and tell your community"
export const Gstep3 = "Many money every time someone buys and unlocks the content"
// export const CREATEGATEDWORKSHOPS = "CREATE GATED CONTENT"
export const CREATEGATEDWORKSHOPS = "MANAGE GATED WORKSHOPS"
export const GatedReview = "DYT Workshops are great way to make money online.I don't have to depend on brand campaigns to earn!"
export const ContentCreator = "Content Creator"
export const PrivacyPolicies = "Privacy Policies"
export const FAQs = "FAQs"
export const TermsConditions = "Terms & Conditions"
export const workShopTime = "1hour 15mins"
export const cardHeading = "How to become a successful influencer in just a day"
export const dateTime = "On 24th June , 2022 at 10:00 AM"
export const WorkshopSH1 = 'Become a host and start creating workshops'
export const WorkshopSH2 = 'Fill In the details in the form to get started'
export const BecomeaHost = "Become a Host"
export const Createworkshop = "Create Workshop"
export const FillTheForm = "Fill up this form to create your workshop"
export const checkoutPage = "Checkout Page"
export const workShopDetailsSub = "How to become a successful influencer in just a dayHow to become a successful influencer in just a day "
export const Enrollments = "Enrollments"
export const Duration = "Duration"
export const workshopOn = "WorkShop On"
export const Whatwillyoulearn = "What will you learn?"
export const whatYouLearnPoints = "The Host not to share the presentation or the recording of the workshop with the attendees unless in special cases, if any."
export const whatYouLearnPoints2 = "Contents of the workshop belong to the Host. DYT in no way assumes any responsibility or ownership of it "
export const whatYouLearnPoints3 = "Cancellation of workshop 2 hours prior to the go-live time will result in penalty. "
export const Rewards = "Rewards"
export const requirements = "Requirements"
export const TandC = "Terms & Conditions"
export const CancellationPolicy = "Cancellation Policy"
export const MyLearnings = " My Learnings"
export const Myworkshops = " Manage Workshops"
export const Exploreworkshops = " Explore Workshops"
export const GatedContentStr = "Gated Contents"
export const UnlockContent = "UNLOCK CONTENT FOR"
export const ContactDetails = "Contact details will be shared during purchase"
export const coupounText = "Now get 20% off by using coupon code DYT20"
export const ExpiresInText = "Expires in 2 days"
export const Creategatedcontent = "Create Gated Content"
export const FillformGated = "Fill up this form to create gated content"
export const GatedContDetails = "Gated Content Details"
export const registerHost = 'To create workshops you need to register as a host .Click on the “Register as Host“ button below to register.'
export const registerUnderReview = "Your host application is under review. We are verifying your details. Expect a response soon."
export const registerSuccess = "You are an instructor on DYT."
export const registerFailure = "Your host application has been rejected. For details, please check your email."
export const registerSuccessDiscription = "Click on the above create workshop button to start creating a workshop."
export const MANAGE_GATED_CONTENT = "MANAGE GATED CONTENT"
export const QA = "Question and Answers section"
export const qaSubHeading = "Write your questions"
export const haveDoubts = 'Have any doubts ? Ask a question'
export const questionSuccess = 'Question added successfully'
export const SuccessMessage = " We'll notify you of responses via email on your registered mail id."
export const notesSubHeading = 'Have something important ? Note it down'
export const reviewRating = "Give Ratings and Write Review"
export const reviewSuccess = 'Review added successfully'
export const reviewsuccessMessage = 'Your review is publically visible to all'
export const WkshpDetail = "Workshop Details"