export const WORKSHOP_LIST_PER_PAGE = 12;
export const WORKSHOP_LIST_INITIAL_OFFSET = 0;
export const GATED_CONTENT_LIST_PER_PAGE = 100;
export const GATED_CONTENT_LIST_INITIAL_OFFSET = 0;
export const WORKSHOP_ATTENDEE_LIST_PER_PAGE = 5;
